// Simulated API Call
const fetchCardData = () => {
  return new Promise((resolve) => {
    // Simulate an asynchronous API call
    setTimeout(() => {
      // Sample Card Data
      const cardData = [
        {
          id: 1,
          playerName: 'LeBron James',
          team: 'Los Angeles Lakers',
          rarity: 'Epic',
          image: 'lebron_james.jpg',
          avgPower: 95,
          stats: { points: 30, rebounds: 10, assists: 8, steals: 2 },
        },
        {
          id: 2,
          playerName: 'Stephen Curry',
          team: 'Golden State Warriors',
          rarity: 'Legendary',
          image: 'stephen_curry.jpg',
          avgPower: 92,
          stats: { points: 28, assists: 12, threePointers: 5 },
        },
        {
          id: 3,
          playerName: 'Giannis Antetokounmpo',
          team: 'Milwaukee Bucks',
          rarity: 'Rare',
          image: 'giannis.jpg',
          avgPower: 89,
          stats: { points: 27, rebounds: 12, assists: 6, blocks: 3 },
        },
        {
          id: 4,
          playerName: 'Kevin Durant',
          team: 'Brooklyn Nets',
          rarity: 'Epic',
          image: 'kevin_durant.jpg',
          avgPower: 94,
          stats: { points: 32, rebounds: 8, assists: 5, blocks: 2 },
        },
        {
          id: 5,
          playerName: 'Kawhi Leonard',
          team: 'LA Clippers',
          rarity: 'Legendary',
          image: 'kawhi_leonard.jpg',
          avgPower: 91,
          stats: { points: 26, rebounds: 9, assists: 4, steals: 3 },
        },
        {
          id: 6,
          playerName: 'Luka Dončić',
          team: 'Dallas Mavericks',
          rarity: 'Rare',
          image: 'luka_doncic.jpg',
          avgPower: 88,
          stats: { points: 29, rebounds: 7, assists: 8, steals: 2 },
        },
        {
          id: 7,
          playerName: 'Anthony Davis',
          team: 'Los Angeles Lakers',
          rarity: 'Epic',
          image: 'anthony_davis.jpg',
          avgPower: 93,
          stats: { points: 28, rebounds: 11, assists: 3, blocks: 2 },
        },
        {
          id: 8,
          playerName: 'James Harden',
          team: 'Brooklyn Nets',
          rarity: 'Legendary',
          image: 'james_harden.jpg',
          avgPower: 90,
          stats: { points: 31, assists: 10, rebounds: 6, steals: 2 },
        },
        {
          id: 9,
          playerName: 'Damian Lillard',
          team: 'Portland Trail Blazers',
          rarity: 'Rare',
          image: 'damian_lillard.jpg',
          avgPower: 87,
          stats: { points: 30, assists: 8, threePointers: 4 },
        },
        {
          id: 10,
          playerName: 'Joel Embiid',
          team: 'Philadelphia 76ers',
          rarity: 'Epic',
          image: 'joel_embiid.jpg',
          avgPower: 92,
          stats: { points: 29, rebounds: 12, assists: 3, blocks: 2 },
        },
        {
          id: 11,
          playerName: 'Jayson Tatum',
          team: 'Boston Celtics',
          rarity: 'Legendary',
          image: 'jayson_tatum.jpg',
          avgPower: 89,
          stats: { points: 27, rebounds: 8, assists: 4, steals: 1 },
        },
        {
          id: 12,
          playerName: 'Devin Booker',
          team: 'Phoenix Suns',
          rarity: 'Rare',
          image: 'devin_booker.jpg',
          avgPower: 88,
          stats: { points: 26, assists: 6, rebounds: 4, steals: 1 },
        },
        {
          id: 13,
          playerName: 'Russell Westbrook',
          team: 'Los Angeles Lakers',
          rarity: 'Epic',
          image: 'russell_westbrook.jpg',
          avgPower: 91,
          stats: { points: 24, assists: 11, rebounds: 8, steals: 2 },
        },
        {
          id: 14,
          playerName: 'Zion Williamson',
          team: 'New Orleans Pelicans',
          rarity: 'Legendary',
          image: 'zion_williamson.jpg',
          avgPower: 90,
          stats: { points: 26, rebounds: 10, assists: 4, blocks: 2 },
        },
        {
          id: 15,
          playerName: 'Ben Simmons',
          team: 'Philadelphia 76ers',
          rarity: 'Rare',
          image: 'ben_simmons.jpg',
          avgPower: 86,
          stats: { points: 16, assists: 9, rebounds: 7, steals: 2 },
        },
        {
          id: 16,
          playerName: 'De\'Aaron Fox',
          team: 'Sacramento Kings',
          rarity: 'Epic',
          image: 'dearon_fox.jpg',
          avgPower: 88,
          stats: { points: 24, assists: 7, rebounds: 4, steals: 1 },
        },
        {
          id: 17,
          playerName: 'Chris Paul',
          team: 'Phoenix Suns',
          rarity: 'Rare',
          image: 'chris_paul.jpg',
          avgPower: 85,
          stats: { points: 18, assists: 10, rebounds: 4, steals: 2 },
        },
        {
          id: 18,
          playerName: 'Karl-Anthony Towns',
          team: 'Minnesota Timberwolves',
          rarity: 'Epic',
          image: 'karl_anthony_towns.jpg',
          avgPower: 89,
          stats: { points: 25, rebounds: 12, assists: 3, blocks: 2 },
        },
        {
          id: 19,
          playerName: 'Jaylen Brown',
          team: 'Boston Celtics',
          rarity: 'Legendary',
          image: 'jaylen_brown.jpg',
          avgPower: 87,
          stats: { points: 24, rebounds: 6, assists: 4, steals: 1 },
        },
        {
          id: 20,
          playerName: 'Jimmy Butler',
          team: 'Miami Heat',
          rarity: 'Rare',
          image: 'jimmy_butler.jpg',
          avgPower: 86,
          stats: { points: 20, rebounds: 7, assists: 5, steals: 2 },
        },
      ];

      resolve(cardData);
    }, 1000); // Simulate a 1-second delay (adjust as needed)
  });
};

export default fetchCardData;
