name: Hello World Comment

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  hello_world_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Crear comentario
      run: |
        COMMENT="Hello world"
        API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"$COMMENT\"}" $API_URL
