name: Get and Print Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  get_and_print_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm list

    - name: Run tests and calculate coverage
      run: |
        npm test -- --coverage
        ls -l coverage

    - name: Get coverage percentage
      id: coverage
      run: |
        COVERAGE=$(sed -n 's/.*<span class="pc_cov">\([^<]*\)<\/span><span class="pc_vis">.*/\1/p' coverage/lcov-report/index.html)
        echo "Test coverage is: $COVERAGE%"

    - name: Print coverage to console
      run: |
        echo "Test coverage is: ${{ steps.coverage.outputs.coverage }}%"
