name: Get and Print Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  get_and_print_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm list

    - name: Run tests and calculate coverage
      run: |
        npm test -- --coverage
        ls -l coverage

    - name: Get coverage percentage
      id: coverage
      run: |
        COVERAGE=$(cat coverage/lcov-report/index.html | grep -oP 'data-stat="[0-9]+" data-value="\K[^"]+')
        echo "Test coverage is: $COVERAGE%"
