name: Test and Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm list

    - name: Run tests and calculate coverage
      run: |
        npm test -- --coverage
        ls -l coverage

    - name: Get coverage percentage
      id: coverage
      run: |
        COVERAGE=$(sed -n 's/.*<span class="pc_cov">\([^<]*\)<\/span><span class="pc_vis">.*/\1/p' coverage/lcov-report/index.html)
        echo "::set-output name=coverage::$COVERAGE"

    - name: Check coverage
      run: |
        COVERAGE=${{ steps.coverage.outputs.coverage }}
        if [ "$COVERAGE" -ge 80 ]; then
          echo "✅ **Acceptable coverage: $COVERAGE%**"
          STATUS="Yes"
          EMOJI="✅"
        else
          echo "❌ **Insufficient coverage. Current: $COVERAGE%**"
          STATUS="No"
          EMOJI="❌"
        fi
        echo "::set-output name=status::$STATUS"
        echo "::set-output name=emoji::$EMOJI"

    - name: Create or update coverage comment
      run: |
        COMMENT_BODY="## Coverage Report\nThe test coverage for this pull request is: **${{ steps.coverage.outputs.coverage }}%**\n${{ steps.status }} *Coverage is above 80%: ${{ steps.status }}*"

        # Get existing comment IDs
        COMMENT_IDS=$(curl -s -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
                         -X GET \
                         "https://api.github.com/repos/jordiadan/nba-react-game/issues/3/comments" | \
                         jq -r '.[] | select(.user.login == "github-actions[bot]" and (.body | contains("## Coverage Report") // false)) | .id')

        # Delete existing comments
        for COMMENT_ID in $COMMENT_IDS; do
          curl -s -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
               -X DELETE \
               "https://api.github.com/repos/jordiadan/nba-react-game/issues/comments/$COMMENT_ID"
        done

        # Create a new comment
        curl -s -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
             -X POST \
             -d '{"body": "'"${COMMENT_BODY}"'"}' \
             "https://api.github.com/repos/jordiadan/nba-react-game/issues/3/comments"
