name: Run Tests and Check Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run_tests_and_check_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: npm test -- --coverage

    - name: Check coverage threshold
      run: |
        # Run tests with coverage and capture the output
        coverage_output=$(npm test -- --coverage 2>&1)

        # Get the total coverage line
        total_coverage_line=$(echo "$coverage_output" | awk '/All files/ {print $4}' | tr -d '%')

        # Print the total coverage
        echo "Total Coverage: $total_coverage_line"

        # Check if coverage is below 80%
        if (( $(echo "$total_coverage_line < 80" | bc -l) )); then
          echo "Coverage is below 80%. Failing the check."
          exit 1
        else
          echo "Coverage is above or equal to 80%. Check passed."
        fi
